# Generated by Django 3.1.7 on 2021-05-05 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('Physical', 'Physical'), ('Mailing', 'Mailing')], default='PHYSICAL', max_length=8)),
                ('address1', models.CharField(max_length=250)),
                ('unit_type', models.CharField(blank=True, choices=[('APT', 'Apartment'), ('STE', 'Suite'), ('BLDG', 'Building'), ('RM', 'Room'), ('SPC', 'Space'), ('UNIT', 'Unit'), ('FL', 'Floor')], max_length=20, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField(verbose_name='Postal Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Agreed Medical Evaluator', 'Agreed Medical Evaluator'), ('Applicant', 'Applicant'), ('Applicant Attorney', 'Applicant Attorney'), ('Attorney', 'Attorney'), ('Claims Adjuster', 'Claims Adjuster'), ('Co-Defendant', 'Co-Defendant'), ('Defendant', 'Defendant'), ('Defense Attorney', 'Defense Attorney'), ('Doctor', 'Doctor'), ('Employee', 'Employee'), ('Employer', 'Employer'), ('Lien Claimant', 'Lien Claimant'), ('Nurse Case Manager', 'Nurse Case Manager'), ('Primary Treating Physician', 'Primary Treating Physician'), ('Qualified Medical Evaluator', 'Qualified Medical Evaluator'), ('Third Party Administrator', 'Third Party Administrator'), ('Other', 'Other')], default='Other', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.ManyToManyField(blank=True, to='contacts.Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Main', 'Main'), ('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell'), ('Fax', 'Fax'), ('Other', 'Other')], default='Main', max_length=5)),
                ('number', models.IntegerField()),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telephone_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telephone_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Agreed Medical Evaluator', 'Agreed Medical Evaluator'), ('Applicant', 'Applicant'), ('Applicant Attorney', 'Applicant Attorney'), ('Attorney', 'Attorney'), ('Claims Adjuster', 'Claims Adjuster'), ('Co-Defendant', 'Co-Defendant'), ('Defendant', 'Defendant'), ('Defense Attorney', 'Defense Attorney'), ('Doctor', 'Doctor'), ('Employee', 'Employee'), ('Employer', 'Employer'), ('Lien Claimant', 'Lien Claimant'), ('Nurse Case Manager', 'Nurse Case Manager'), ('Primary Treating Physician', 'Primary Treating Physician'), ('Qualified Medical Evaluator', 'Qualified Medical Evaluator'), ('Third Party Administrator', 'Third Party Administrator'), ('Other', 'Other')], default='Other', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Hon.', 'Hon.')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('Esq.', 'Esq.'), ('J.D.', 'J.D.'), ('M.D.', 'M.D.'), ('Ph.D.', 'Ph.D.'), ('Psy.D.', 'Psy.D.'), ('D.D.S.', 'D.D.S.'), ('D.P.M.', 'D.P.M.'), ('D.O.', 'D.O.'), ('D.M.D.', 'D.M.D.'), ('N.P.', 'N.P.'), ('O.D.', 'O.D.'), ('P.A.', 'P.A.')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('ssn', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Social Security Number')),
                ('address', models.ManyToManyField(blank=True, to='contacts.Address')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_created_by', to=settings.AUTH_USER_MODEL)),
                ('email', models.ManyToManyField(blank=True, to='contacts.Email')),
                ('telephone', models.ManyToManyField(blank=True, to='contacts.Telephone')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.ManyToManyField(blank=True, to='contacts.Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.ManyToManyField(blank=True, to='contacts.Telephone'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
