# Generated by Django 3.1.7 on 2021-04-28 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('TR', 'Trialing'), ('AC', 'Active'), ('IN', 'Incomplete'), ('IP', 'Incomplete Expired'), ('PD', 'Past Due'), ('CA', 'Canceled'), ('UN', 'Unpaid')], default='TR', max_length=120)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancel_at', models.DateTimeField(null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.stripecustomer')),
            ],
        ),
    ]
